### ISSUE TITLE
LOTTI_joint+link_modified

### ISSUE THREAD

**Issue by eunji9128** [teamlotto/LottoWorld_create#1]
![LOTTI_joint_modified](https://user-images.githubusercontent.com/80051721/131602707-43439c75-a964-4521-b8b3-1c6cfc95f0dd.gif)

**Comment by ChaejinE** [comment]
# 문제
## 1. 재생시 Lidar가 돌아버린다
![strange_lidar](https://user-images.githubusercontent.com/69780812/131615881-c3b6c6db-359c-48f8-92f1-36d1d60bcae0.gif)
- Lidar 강체, 충돌체 속성 없애니 됨
## 2. Lidar가 좌표를 따라서 같이 안움직인ㄷ ㅏ?
![strange_lidar2](https://user-images.githubusercontent.com/69780812/131616470-8d8cd490-dd9b-4742-90b3-fce3225689f4.gif)

**Comment by eunji9128** [comment]
https://github.com/teamlotto/Isaac-Sim-Warehouse/issues/11#issue-984815226
위 이슈에서 팔로업
